# Generated by Django 3.0.8 on 2021-06-06 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, unique=True)),
                ('day', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('alias', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('entrada', models.CharField(max_length=50)),
                ('plato_fuerte', models.CharField(max_length=50)),
                ('postre', models.CharField(max_length=50)),
                ('ensalada', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_comments', models.CharField(max_length=250)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu_app.Calendar')),
                ('menu_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu_app.Menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='MenuSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu_app.Calendar')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu_app.Menu')),
            ],
        ),
    ]
