# Generated by Django 3.0.8 on 2021-06-06 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_comments', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='userchoice',
            name='date',
        ),
        migrations.RemoveField(
            model_name='userchoice',
            name='menu_name',
        ),
        migrations.RemoveField(
            model_name='userchoice',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='menuschedule',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-email']},
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='entrada',
            new_name='appetizers',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='postre',
            new_name='desert',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='plato_fuerte',
            new_name='main_meal',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='nombre',
            new_name='meal_name',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='ensalada',
            new_name='salad',
        ),
        migrations.RemoveField(
            model_name='menuschedule',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='menuschedule',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menuschedule',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_app.Menu'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
        migrations.DeleteModel(
            name='UserChoice',
        ),
        migrations.AddField(
            model_name='userschoice',
            name='scheduled_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_app.MenuSchedule'),
        ),
        migrations.AddField(
            model_name='userschoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_app.User'),
        ),
    ]
