# Generated by Django 3.0.8 on 2021-06-06 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0004_auto_20210606_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuschedule',
            name='alias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_app.Menu'),
        ),
    ]
